namespace Ninu
{
    public enum DirectInputButton
    {
        // Keyboard
        KeyboardUnknown = 0,
        KeyboardEscape = 1,
        KeyboardD1 = 2,
        KeyboardD2 = 3,
        KeyboardD3 = 4,
        KeyboardD4 = 5,
        KeyboardD5 = 6,
        KeyboardD6 = 7,
        KeyboardD7 = 8,
        KeyboardD8 = 9,
        KeyboardD9 = 10,
        KeyboardD0 = 11,
        KeyboardMinus = 12,
        KeyboardEquals = 13,
        KeyboardBack = 14,
        KeyboardTab = 15,
        KeyboardQ = 16,
        KeyboardW = 17,
        KeyboardE = 18,
        KeyboardR = 19,
        KeyboardT = 20,
        KeyboardY = 21,
        KeyboardU = 22,
        KeyboardI = 23,
        KeyboardO = 24,
        KeyboardP = 25,
        KeyboardLeftBracket = 26,
        KeyboardRightBracket = 27,
        KeyboardReturn = 28,
        KeyboardLeftControl = 29,
        KeyboardA = 30,
        KeyboardS = 31,
        KeyboardD = 32,
        KeyboardF = 33,
        KeyboardG = 34,
        KeyboardH = 35,
        KeyboardJ = 36,
        KeyboardK = 37,
        KeyboardL = 38,
        KeyboardSemicolon = 39,
        KeyboardApostrophe = 40,
        KeyboardGrave = 41,
        KeyboardLeftShift = 42,
        KeyboardBackslash = 43,
        KeyboardZ = 44,
        KeyboardX = 45,
        KeyboardC = 46,
        KeyboardV = 47,
        KeyboardB = 48,
        KeyboardN = 49,
        KeyboardM = 50,
        KeyboardComma = 51,
        KeyboardPeriod = 52,
        KeyboardSlash = 53,
        KeyboardRightShift = 54,
        KeyboardMultiply = 55,
        KeyboardLeftAlt = 56,
        KeyboardSpace = 57,
        KeyboardCapital = 58,
        KeyboardF1 = 59,
        KeyboardF2 = 60,
        KeyboardF3 = 61,
        KeyboardF4 = 62,
        KeyboardF5 = 63,
        KeyboardF6 = 64,
        KeyboardF7 = 65,
        KeyboardF8 = 66,
        KeyboardF9 = 67,
        KeyboardF10 = 68,
        KeyboardNumberLock = 69,
        KeyboardScrollLock = 70,
        KeyboardNumberPad7 = 71,
        KeyboardNumberPad8 = 72,
        KeyboardNumberPad9 = 73,
        KeyboardSubtract = 74,
        KeyboardNumberPad4 = 75,
        KeyboardNumberPad5 = 76,
        KeyboardNumberPad6 = 77,
        KeyboardAdd = 78,
        KeyboardNumberPad1 = 79,
        KeyboardNumberPad2 = 80,
        KeyboardNumberPad3 = 81,
        KeyboardNumberPad0 = 82,
        KeyboardDecimal = 83,
        KeyboardOem102 = 86,
        KeyboardF11 = 87,
        KeyboardF12 = 88,
        KeyboardF13 = 100,
        KeyboardF14 = 101,
        KeyboardF15 = 102,
        KeyboardKana = 112,
        KeyboardAbntC1 = 115,
        KeyboardConvert = 121,
        KeyboardNoConvert = 123,
        KeyboardYen = 125,
        KeyboardAbntC2 = 126,
        KeyboardNumberPadEquals = 141,
        KeyboardPreviousTrack = 144,
        KeyboardAT = 145,
        KeyboardColon = 146,
        KeyboardUnderline = 147,
        KeyboardKanji = 148,
        KeyboardStop = 149,
        KeyboardAX = 150,
        KeyboardUnlabeled = 151,
        KeyboardNextTrack = 153,
        KeyboardNumberPadEnter = 156,
        KeyboardRightControl = 157,
        KeyboardMute = 160,
        KeyboardCalculator = 161,
        KeyboardPlayPause = 162,
        KeyboardMediaStop = 164,
        KeyboardVolumeDown = 174,
        KeyboardVolumeUp = 176,
        KeyboardWebHome = 178,
        KeyboardNumberPadComma = 179,
        KeyboardDivide = 181,
        KeyboardPrintScreen = 183,
        KeyboardRightAlt = 184,
        KeyboardPause = 197,
        KeyboardHome = 199,
        KeyboardUp = 200,
        KeyboardPageUp = 201,
        KeyboardLeft = 203,
        KeyboardRight = 205,
        KeyboardEnd = 207,
        KeyboardDown = 208,
        KeyboardPageDown = 209,
        KeyboardInsert = 210,
        KeyboardDelete = 211,
        KeyboardLeftWindowsKey = 219,
        KeyboardRightWindowsKey = 220,
        KeyboardApplications = 221,
        KeyboardPower = 222,
        KeyboardSleep = 223,
        KeyboardWake = 227,
        KeyboardWebSearch = 229,
        KeyboardWebFavorites = 230,
        KeyboardWebRefresh = 231,
        KeyboardWebStop = 232,
        KeyboardWebForward = 233,
        KeyboardWebBack = 234,
        KeyboardMyComputer = 235,
        KeyboardMail = 236,
        KeyboardMediaSelect = 237,

        // Joysticks
        JoystickButton1 = 1000,
        JoystickButton2,
        JoystickButton3,
        JoystickButton4,
        JoystickButton5,
        JoystickButton6,
        JoystickButton7,
        JoystickButton8,
        JoystickButton9,
        JoystickButton10,
        JoystickButton11,
        JoystickButton12,
        JoystickButton13,
        JoystickButton14,
        JoystickButton15,
        JoystickButton16,
        JoystickButton17,
        JoystickButton18,
        JoystickButton19,
        JoystickButton20,
        JoystickButton21,
        JoystickButton22,
        JoystickButton23,
        JoystickButton24,
        JoystickButton25,
        JoystickButton26,
        JoystickButton27,
        JoystickButton28,
        JoystickButton29,
        JoystickButton30,
        JoystickButton31,
        JoystickButton32,
        JoystickButton33,
        JoystickButton34,
        JoystickButton35,
        JoystickButton36,
        JoystickButton37,
        JoystickButton38,
        JoystickButton39,
        JoystickButton40,
        JoystickButton41,
        JoystickButton42,
        JoystickButton43,
        JoystickButton44,
        JoystickButton45,
        JoystickButton46,
        JoystickButton47,
        JoystickButton48,
        JoystickButton49,
        JoystickButton50,
        JoystickButton51,
        JoystickButton52,
        JoystickButton53,
        JoystickButton54,
        JoystickButton55,
        JoystickButton56,
        JoystickButton57,
        JoystickButton58,
        JoystickButton59,
        JoystickButton60,
        JoystickButton61,
        JoystickButton62,
        JoystickButton63,
        JoystickButton64,
        JoystickButton65,
        JoystickButton66,
        JoystickButton67,
        JoystickButton68,
        JoystickButton69,
        JoystickButton70,
        JoystickButton71,
        JoystickButton72,
        JoystickButton73,
        JoystickButton74,
        JoystickButton75,
        JoystickButton76,
        JoystickButton77,
        JoystickButton78,
        JoystickButton79,
        JoystickButton80,
        JoystickButton81,
        JoystickButton82,
        JoystickButton83,
        JoystickButton84,
        JoystickButton85,
        JoystickButton86,
        JoystickButton87,
        JoystickButton88,
        JoystickButton89,
        JoystickButton90,
        JoystickButton91,
        JoystickButton92,
        JoystickButton93,
        JoystickButton94,
        JoystickButton95,
        JoystickButton96,
        JoystickButton97,
        JoystickButton98,
        JoystickButton99,
        JoystickButton100,
        JoystickButton101,
        JoystickButton102,
        JoystickButton103,
        JoystickButton104,
        JoystickButton105,
        JoystickButton106,
        JoystickButton107,
        JoystickButton108,
        JoystickButton109,
        JoystickButton110,
        JoystickButton111,
        JoystickButton112,
        JoystickButton113,
        JoystickButton114,
        JoystickButton115,
        JoystickButton116,
        JoystickButton117,
        JoystickButton118,
        JoystickButton119,
        JoystickButton120,
        JoystickButton121,
        JoystickButton122,
        JoystickButton123,
        JoystickButton124,
        JoystickButton125,
        JoystickButton126,
        JoystickButton127,
        JoystickButton128,

        JoystickPov0North,
        JoystickPov0East,
        JoystickPov0South,
        JoystickPov0West,
        JoystickPov1North,
        JoystickPov1East,
        JoystickPov1South,
        JoystickPov1West,
        JoystickPov2North,
        JoystickPov2East,
        JoystickPov2South,
        JoystickPov2West,
        JoystickPov3North,
        JoystickPov3East,
        JoystickPov3South,
        JoystickPov3West,
    }
}