namespace Ninu.Emulator.CentralProcessor
{
    public enum NewOpcode : byte
    {
        Brk_Implied = 0x00,
        Ora_IndirectZeroPageXIndexed = 0x01,
        Kil_Implied_02 = 0x02, // Illegal
        Slo_IndirectZeroPageXIndexed_03 = 0x03, // Illegal
        Nop_ZeroPage_04 = 0x04, // Illegal
        Ora_ZeroPage = 0x05,
        Asl_ZeroPage = 0x06,
        Slo_ZeroPage_07 = 0x07, // Illegal
        Php_Implied = 0x08,
        Ora_Immediate = 0x09,
        Asl_Accumulator = 0x0A,
        Anc_Immediate_0B = 0x0B, // Illegal
        Nop_Absolute_0C = 0x0C, // Illegal
        Ora_Absolute = 0x0D,
        Asl_Absolute = 0x0E,
        Slo_Absolute_0F = 0x0F, // Illegal
        Bpl_Relative = 0x10,
        Ora_IndirectZeroPageYIndexed = 0x11,
        Kil_Implied_12 = 0x12, // Illegal
        Slo_IndirectZeroPageYIndexed_13 = 0x13, // Illegal
        Nop_ZeroPageXIndexed_14 = 0x14, // Illegal
        Ora_ZeroPageXIndexed = 0x15,
        Asl_ZeroPageXIndexed = 0x16,
        Slo_ZeroPageXIndexed_17 = 0x17, // Illegal
        Clc_Implied = 0x18,
        Ora_AbsoluteYIndexed = 0x19,
        Nop_Implied_1A = 0x1A, // Illegal
        Slo_AbsoluteYIndexed_1B = 0x1B, // Illegal
        Nop_AbsoluteXIndexed_1C = 0x1C, // Illegal
        Ora_AbsoluteXIndexed = 0x1D,
        Asl_AbsoluteXIndexed = 0x1E,
        Slo_AbsoluteXIndexed_1F = 0x1F, // Illegal
        Jsr_Absolute = 0x20,
        And_IndirectZeroPageXIndexed = 0x21,
        Kil_Implied_22 = 0x22, // Illegal
        Rla_IndirectZeroPageXIndexed_23 = 0x23, // Illegal
        Bit_ZeroPage = 0x24,
        And_ZeroPage = 0x25,
        Rol_ZeroPage = 0x26,
        Rla_ZeroPage_27 = 0x27, // Illegal
        Plp_Implied = 0x28,
        And_Immediate = 0x29,
        Rol_Accumulator = 0x2A,
        Anc_Immediate_2B = 0x2B, // Illegal
        Bit_Absolute = 0x2C,
        And_Absolute = 0x2D,
        Rol_Absolute = 0x2E,
        Rla_Absolute_2F = 0x2F, // Illegal
        Bmi_Relative = 0x30,
        And_IndirectZeroPageYIndexed = 0x31,
        Kil_Implied_32 = 0x32, // Illegal
        Rla_IndirectZeroPageYIndexed_33 = 0x33, // Illegal
        Nop_ZeroPageXIndexed_34 = 0x34, // Illegal
        And_ZeroPageXIndexed = 0x35,
        Rol_ZeroPageXIndexed = 0x36,
        Rla_ZeroPageXIndexed_37 = 0x37, // Illegal
        Sec_Implied = 0x38,
        And_AbsoluteYIndexed = 0x39,
        Nop_Implied_3A = 0x3A, // Illegal
        Rla_AbsoluteYIndexed_3B = 0x3B, // Illegal
        Nop_AbsoluteXIndexed_3C = 0x3C, // Illegal
        And_AbsoluteXIndexed = 0x3D,
        Rol_AbsoluteXIndexed = 0x3E,
        Rla_AbsoluteXIndexed_3F = 0x3F, // Illegal
        Rti_Implied = 0x40,
        Eor_IndirectZeroPageXIndexed = 0x41,
        Kil_Implied_42 = 0x42, // Illegal
        Sre_IndirectZeroPageXIndexed_43 = 0x43, // Illegal
        Nop_ZeroPage_44 = 0x44, // Illegal
        Eor_ZeroPage = 0x45,
        Lsr_ZeroPage = 0x46,
        Sre_ZeroPage_47 = 0x47, // Illegal
        Pha_Implied = 0x48,
        Eor_Immediate = 0x49,
        Lsr_Accumulator = 0x4A,
        Alr_Immediate_4B = 0x4B, // Illegal
        Jmp_Absolute = 0x4C,
        Eor_Absolute = 0x4D,
        Lsr_Absolute = 0x4E,
        Sre_Absolute_4F = 0x4F, // Illegal
        Bvc_Relative = 0x50,
        Eor_IndirectZeroPageYIndexed = 0x51,
        Kil_Implied_52 = 0x52, // Illegal
        Sre_IndirectZeroPageYIndexed_53 = 0x53, // Illegal
        Nop_ZeroPageXIndexed_54 = 0x54, // Illegal
        Eor_ZeroPageXIndexed = 0x55,
        Lsr_ZeroPageXIndexed = 0x56,
        Sre_ZeroPageXIndexed_57 = 0x57, // Illegal
        Cli_Implied = 0x58,
        Eor_AbsoluteYIndexed = 0x59,
        Nop_Implied_5A = 0x5A, // Illegal
        Sre_AbsoluteYIndexed_5B = 0x5B, // Illegal
        Nop_AbsoluteXIndexed_5C = 0x5C, // Illegal
        Eor_AbsoluteXIndexed = 0x5D,
        Lsr_AbsoluteXIndexed = 0x5E,
        Sre_AbsoluteXIndexed_5F = 0x5F, // Illegal
        Rts_Implied = 0x60,
        Adc_IndirectZeroPageXIndexed = 0x61,
        Kil_Implied_62 = 0x62, // Illegal
        Rra_IndirectZeroPageXIndexed_63 = 0x63, // Illegal
        Nop_ZeroPage_64 = 0x64, // Illegal
        Adc_ZeroPage = 0x65,
        Ror_ZeroPage = 0x66,
        Rra_ZeroPage_67 = 0x67, // Illegal
        Pla_Implied = 0x68,
        Adc_Immediate = 0x69,
        Ror_Accumulator = 0x6A,
        Arr_Immediate_6B = 0x6B, // Illegal
        Jmp_Indirect = 0x6C,
        Adc_Absolute = 0x6D,
        Ror_Absolute = 0x6E,
        Rra_Absolute_6F = 0x6F, // Illegal
        Bvs_Relative = 0x70,
        Adc_IndirectZeroPageYIndexed = 0x71,
        Kil_Implied_72 = 0x72, // Illegal
        Rra_IndirectZeroPageYIndexed_73 = 0x73, // Illegal
        Nop_ZeroPageXIndexed_74 = 0x74, // Illegal
        Adc_ZeroPageXIndexed = 0x75,
        Ror_ZeroPageXIndexed = 0x76,
        Rra_ZeroPageXIndexed_77 = 0x77, // Illegal
        Sei_Implied = 0x78,
        Adc_AbsoluteYIndexed = 0x79,
        Nop_Implied_7A = 0x7A, // Illegal
        Rra_AbsoluteYIndexed_7B = 0x7B, // Illegal
        Nop_AbsoluteXIndexed_7C = 0x7C, // Illegal
        Adc_AbsoluteXIndexed = 0x7D,
        Ror_AbsoluteXIndexed = 0x7E,
        Rra_AbsoluteXIndexed_7F = 0x7F, // Illegal
        Nop_Immediate_80 = 0x80, // Illegal
        Sta_IndirectZeroPageXIndexed = 0x81,
        Nop_Immediate_82 = 0x82, // Illegal
        Sax_IndirectZeroPageXIndexed_83 = 0x83, // Illegal
        Sty_ZeroPage = 0x84,
        Sta_ZeroPage = 0x85,
        Stx_ZeroPage = 0x86,
        Sax_ZeroPage_87 = 0x87, // Illegal
        Dey_Implied = 0x88,
        Nop_Immediate_89 = 0x89, // Illegal
        Txa_Implied = 0x8A,
        Xaa_Immediate_8B = 0x8B, // Illegal
        Sty_Absolute = 0x8C,
        Sta_Absolute = 0x8D,
        Stx_Absolute = 0x8E,
        Sax_Absolute_8F = 0x8F, // Illegal
        Bcc_Relative = 0x90,
        Sta_IndirectZeroPageYIndexed = 0x91,
        Kil_Implied_92 = 0x92, // Illegal
        Ahx_IndirectZeroPageYIndexed_93 = 0x93, // Illegal
        Sty_ZeroPageXIndexed = 0x94,
        Sta_ZeroPageXIndexed = 0x95,
        Stx_ZeroPageYIndexed = 0x96,
        Sax_ZeroPageYIndexed_97 = 0x97, // Illegal
        Tya_Implied = 0x98,
        Sta_AbsoluteYIndexed = 0x99,
        Txs_Implied = 0x9A,
        Tas_AbsoluteYIndexed_9B = 0x9B, // Illegal
        Shy_AbsoluteXIndexed_9C = 0x9C, // Illegal
        Sta_AbsoluteXIndexed = 0x9D,
        Shx_AbsoluteYIndexed_9E = 0x9E, // Illegal
        Ahx_AbsoluteYIndexed_9F = 0x9F, // Illegal
        Ldy_Immediate = 0xA0,
        Lda_IndirectZeroPageXIndexed = 0xA1,
        Ldx_Immediate = 0xA2,
        Lax_IndirectZeroPageXIndexed_A3 = 0xA3, // Illegal
        Ldy_ZeroPage = 0xA4,
        Lda_ZeroPage = 0xA5,
        Ldx_ZeroPage = 0xA6,
        Lax_ZeroPage_A7 = 0xA7, // Illegal
        Tay_Implied = 0xA8,
        Lda_Immediate = 0xA9,
        Tax_Implied = 0xAA,
        Lax_Immediate_AB = 0xAB, // Illegal
        Ldy_Absolute = 0xAC,
        Lda_Absolute = 0xAD,
        Ldx_Absolute = 0xAE,
        Lax_Absolute_AF = 0xAF, // Illegal
        Bcs_Relative = 0xB0,
        Lda_IndirectZeroPageYIndexed = 0xB1,
        Kil_Implied_B2 = 0xB2, // Illegal
        Lax_IndirectZeroPageYIndexed_B3 = 0xB3, // Illegal
        Ldy_ZeroPageXIndexed = 0xB4,
        Lda_ZeroPageXIndexed = 0xB5,
        Ldx_ZeroPageYIndexed = 0xB6,
        Lax_ZeroPageYIndexed_B7 = 0xB7, // Illegal
        Clv_Implied = 0xB8,
        Lda_AbsoluteYIndexed = 0xB9,
        Tsx_Implied = 0xBA,
        Las_AbsoluteYIndexed_BB = 0xBB, // Illegal
        Ldy_AbsoluteXIndexed = 0xBC,
        Lda_AbsoluteXIndexed = 0xBD,
        Ldx_AbsoluteYIndexed = 0xBE,
        Lax_AbsoluteYIndexed_BF = 0xBF, // Illegal
        Cpy_Immediate = 0xC0,
        Cmp_IndirectZeroPageXIndexed = 0xC1,
        Nop_Immediate_C2 = 0xC2, // Illegal
        Dcp_IndirectZeroPageXIndexed_C3 = 0xC3, // Illegal
        Cpy_ZeroPage = 0xC4,
        Cmp_ZeroPage = 0xC5,
        Dec_ZeroPage = 0xC6,
        Dcp_ZeroPage_C7 = 0xC7, // Illegal
        Iny_Implied = 0xC8,
        Cmp_Immediate = 0xC9,
        Dex_Implied = 0xCA,
        Axs_Immediate_CB = 0xCB, // Illegal
        Cpy_Absolute = 0xCC,
        Cmp_Absolute = 0xCD,
        Dec_Absolute = 0xCE,
        Dcp_Absolute_CF = 0xCF, // Illegal
        Bne_Relative = 0xD0,
        Cmp_IndirectZeroPageYIndexed = 0xD1,
        Kil_Implied_D2 = 0xD2, // Illegal
        Dcp_IndirectZeroPageYIndexed_D3 = 0xD3, // Illegal
        Nop_ZeroPageXIndexed_D4 = 0xD4, // Illegal
        Cmp_ZeroPageXIndexed = 0xD5,
        Dec_ZeroPageXIndexed = 0xD6,
        Dcp_ZeroPageXIndexed_D7 = 0xD7, // Illegal
        Cld_Implied = 0xD8,
        Cmp_AbsoluteYIndexed = 0xD9,
        Nop_Implied_DA = 0xDA, // Illegal
        Dcp_AbsoluteYIndexed_DB = 0xDB, // Illegal
        Nop_AbsoluteXIndexed_DC = 0xDC, // Illegal
        Cmp_AbsoluteXIndexed = 0xDD,
        Dec_AbsoluteXIndexed = 0xDE,
        Dcp_AbsoluteXIndexed_DF = 0xDF, // Illegal
        Cpx_Immediate = 0xE0,
        Sbc_IndirectZeroPageXIndexed = 0xE1,
        Nop_Immediate_E2 = 0xE2, // Illegal
        Isc_IndirectZeroPageXIndexed_E3 = 0xE3, // Illegal
        Cpx_ZeroPage = 0xE4,
        Sbc_ZeroPage = 0xE5,
        Inc_ZeroPage = 0xE6,
        Isc_ZeroPage_E7 = 0xE7, // Illegal
        Inx_Implied = 0xE8,
        Sbc_Immediate = 0xE9,
        Nop_Implied = 0xEA,
        Sbc_Immediate_EB = 0xEB, // Illegal
        Cpx_Absolute = 0xEC,
        Sbc_Absolute = 0xED,
        Inc_Absolute = 0xEE,
        Isc_Absolute_EF = 0xEF, // Illegal
        Beq_Relative = 0xF0,
        Sbc_IndirectZeroPageYIndexed = 0xF1,
        Kil_Implied_F2 = 0xF2, // Illegal
        Isc_IndirectZeroPageYIndexed_F3 = 0xF3, // Illegal
        Nop_ZeroPageXIndexed_F4 = 0xF4, // Illegal
        Sbc_ZeroPageXIndexed = 0xF5,
        Inc_ZeroPageXIndexed = 0xF6,
        Isc_ZeroPageXIndexed_F7 = 0xF7, // Illegal
        Sed_Implied = 0xF8,
        Sbc_AbsoluteYIndexed = 0xF9,
        Nop_Implied_FA = 0xFA, // Illegal
        Isc_AbsoluteYIndexed_FB = 0xFB, // Illegal
        Nop_AbsoluteXIndexed_FC = 0xFC, // Illegal
        Sbc_AbsoluteXIndexed = 0xFD,
        Inc_AbsoluteXIndexed = 0xFE,
        Isc_AbsoluteXIndexed_FF = 0xFF, // Illegal
    }
}